version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: invoice_hub_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: invoice_hub
      MYSQL_USER: your_username
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
